Revert changes to SpacemanDMM/nanomap-renderer
Note that during map generation this will cause errors in the form of:
```
error: #error Your version of BYOND is too out-of-date to compile this project. Go to https://secure.byond.com/download and update.
error: #error You need version 514.1554 or higher
```