Fix render_nanomaps action (#21151)
* Fix render_nanomaps action

Use up-to-date VM and updated SpacemanDMM with modified source

* Revert changes to SpacemanDMM/nanomap-renderer

Note that during map generation this will cause errors in the form of:
```
error: #error Your version of BYOND is too out-of-date to compile this project. Go to https://secure.byond.com/download and update.
error: #error You need version 514.1554 or higher
```